language: php

php:
  - 5.6
  - 7.0

env:
  global:
    - setup=basic

matrix:
  allow_failures:
    - php: 5.6
      env: setup=lowest
    - php: 5.6
      env: setup=stable

sudo: false

before_install:
  - travis_retry composer self-update
  - cp .env.travis .env

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi
  - php artisan key:generate

script: vendor/bin/phpunit